### ISSUE TITLE
Trouble in running the binary

### ISSUE THREAD

**Issue by 0xameer** [myme/nixon#1]
without patchelf -
no such file
with p/e - 
nixon: symbol lookup error: /nix/store/ayrsyv7npr0lcbann4k9lxr19x813f0z-glibc-2.34-115/lib/libc.so.6: undefined symbol: __nptl_change_stack_perm, version GLIBC_PRIVATE

**Comment by myme** [comment]
Not a whole lot to go with on this one. It would be good to know which steps were made, like:

* How was the binary built?
* Was it run directly from `./result/bin/nixon`
* How was `patchelf` applied (and why was it needed in the first place)

I don't really understand why `patchelf` was needed here in the first place. Should be needed if it's built with `nix` and it should also be possible to build this using plain `cabal`.
